TrajectoryPlannerROS:
 max_vel_x: 0.8
 min_vel_x: 0.1
 max_vel_theta: 3.5 #default : 2.5
 min_vel_theta: -3.5 #default : -2.5
 min_in_place_vel_theta: 0.15
 acc_lim_theta: 1
 acc_lim_x: 0.2
 acc_lim_Y: 0.2
 holonomic_robot: false
 meter_scoring: true 
 xy_goal_tolerance: 0.05
 yaw_goal_tolerance: 0.01
 meter_scoring: true
 occdist_scale:  0.01
 pdist_scale: 0.4
 gdist_scale: 0.2
