prm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'rev_left'
    right_wheel: 'rev_right'
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  camera_pan_controller:
    type: "effort_controllers/JointPositionController"
    joint: "pan_joint"
    pid: {p: 0.5, i: 0.5, d: 0.0} #Attention, d peut rendre le modele extremement instable

  camera_tilt_controller:
    type: "effort_controllers/JointPositionController"
    joint: "tilt_joint"
    pid: {p: 0.5, i: 0.5, d: 0.0}
