TrajectoryPlannerROS:
 max_vel_x: 0.8
 min_vel_x: 0.1
 max_vel_theta: 2.5
 min_vel_theta: -2.5
 min_in_place_vel_theta: 0.1
 acc_lim_theta: 0.5
 acc_lim_x: 0.5
 acc_lim_Y: 0.5
 holonomic_robot: false
 meter_scoring: true 
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.1
 meter_scoring: true
 occdist_scale:  0.01
 pdist_scale: 0.4
 gdist_scale: 0.2
